Jakarta csv2bufr
wmo-im/wis2box-training pull request #86
Opened 2023-10-02 16:21 UTC by david-i-berry

- Update of CSV2bufr material to use web-app. 
- Addition of BUFR CLI tools
- Some tidy up and consistency edits.

2023-10-02 18:01 UTC, maaikelimper reviewed
Could you please add the instruction to generate the token for "processes/wis2box" as part of the preparation for synop2bufr-section

Could you please mention to on/off toggle for WIS2 notifications and ask the participant to validate notifications where made on his/her wis2box-broker using MQTT explorer, in both synop2bufr and csv2bufr section

2023-10-03 11:47 UTC, tomkralidis requested changes

2023-10-03 11:47 UTC, tomkralidis commented on documentation/docs/practical-sessions/converting-synop-data-to-bufr.md
> +    - Make sure that you have MQTT explorer open and connected to your broker.
MQTT Explorer

2023-10-03 11:47 UTC, tomkralidis commented on documentation/docs/practical-sessions/converting-synop-data-to-bufr.md
> +the appropriate topic to publish the data on, enter the "processes/wis2box" token and make sure the "publish to WIS2"
`make sure the "publish to WIS" checkbox is checked`?

2023-10-03 11:47 UTC, tomkralidis commented on documentation/docs/practical-sessions/converting-synop-data-to-bufr.md
> +You should also be able to see these notifications in MQTT explorer.
MQTT Explorer.

2023-10-03 12:31 UTC, tomkralidis approved these changes

2023-10-03 12:31 UTC, merged